### ISSUE TITLE
Are you planning to update your code/version also with the new Webserver etc from MiczFlor?

### ISSUE THREAD

**Issue by axelslade** [keinkurt/RPi-Jukebox-RFID#3]
Are you planning to update your code/version also with the new Webserver etc from MiczFlor?

**Comment by MalteHST** [comment]
If you want to use the RC522 module with the new release 1.0 from MiczFlor, you only need to copy the MFRC522.py file into the scripts folder and replace Reader.py and daemon_rfid_reader.py file/code with the ones from @keinkurt. 

Additionally you have to run:
```
git clone https://github.com/lthiery/SPI-Py.git
cd /home/pi/SPI-Py
sudo python setup.py install
```

I can confirm the function off the branch 'stop_on_removal' with the following setup:
Pi Zero W + RC522 + PHATBeat (Pimoroni) + Release 1.0

The only non-functioning feature is the 'resume-play' (interesting especially for audiobooks). 
@keinkurt: Do you have an idea how to integrate this feature into the new release 1.0?

**Comment by keinkurt** [comment]
The master is up-to-date now, including the PR https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/235 which add the possibility to choose the RC522 module at the installation process.
